CREATE TABLE ALBUM (
	ALBUM_KEY            bigint  NOT NULL  AUTO_INCREMENT  PRIMARY KEY,
	ALBUM_ID             char(14)  NOT NULL    ,
	TITLE                varchar(150)  NOT NULL    ,
	DELETED              char(1)  NOT NULL,
	CREATE_UTC           timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP   ,
	CONSTRAINT IDX_ALBUM_UNIQUE_ALBUM_ID UNIQUE ( ALBUM_ID ) 
 ) DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_ALBUM_TITLE ON ALBUM ( TITLE );

ALTER TABLE ALBUM COMMENT '앨범 정보 테이블';

ALTER TABLE ALBUM MODIFY ALBUM_KEY bigint  NOT NULL  AUTO_INCREMENT COMMENT '레코드 식별자';

ALTER TABLE ALBUM MODIFY ALBUM_ID char(14)  NOT NULL   COMMENT '앨범 레코드 대체 식별자';

ALTER TABLE ALBUM MODIFY TITLE varchar(150)  NOT NULL   COMMENT '앨범 타이틀';

ALTER TABLE ALBUM MODIFY DELETED char(1)  NOT NULL   COMMENT '삭제 여부';

ALTER TABLE ALBUM MODIFY CREATE_UTC timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '레코드 생성일시';

CREATE TABLE SONG ( 
	SONG_KEY             bigint  NOT NULL  AUTO_INCREMENT  PRIMARY KEY,
	SONG_ID              char(14)  NOT NULL    ,
	ALBUM_KEY            bigint  NOT NULL    ,
	TITLE                varchar(150)  NOT NULL    ,
	`LENGTH`               int  NOT NULL    ,
	TRACK_NO             tinyint  NOT NULL    ,
	DELETED              char(1)  NOT NULL,
	CREATE_UTC           timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP   ,
	CONSTRAINT IDX_SONG_UNIQUE_SONG_ID UNIQUE ( SONG_ID )
 ) DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_SONG_TITLE ON SONG ( TITLE );

ALTER TABLE SONG COMMENT '곡 정보 테이블';

ALTER TABLE SONG MODIFY SONG_KEY bigint  NOT NULL  AUTO_INCREMENT COMMENT '레코드 식별자';

ALTER TABLE SONG MODIFY SONG_ID char(14)  NOT NULL   COMMENT '레코드 대체 식별자';

ALTER TABLE SONG MODIFY ALBUM_KEY bigint  NOT NULL   COMMENT '소속 앨범 레코드 식별자';

ALTER TABLE SONG MODIFY TITLE varchar(150)  NOT NULL   COMMENT '제목';

ALTER TABLE SONG MODIFY LENGTH int  NOT NULL   COMMENT '곡 길이';

ALTER TABLE SONG MODIFY TRACK_NO tinyint  NOT NULL   COMMENT '트랙 번호';

ALTER TABLE SONG MODIFY DELETED char(1) NOT NULL   COMMENT '삭제 여부';

ALTER TABLE SONG MODIFY CREATE_UTC timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '레코드 생성일시';